from hashlib import sha512

from colabfit.tools.pg.utilities import (
    ELEMENT_MAP,
    _empty_dict_from_schema,
    get_last_modified,
)
from colabfit.tools.pg.schema import configuration_set_schema


class ConfigurationSet:
    """
    A configuration set defines a group of configurations and aggregates
    information about those configurations to improve queries.

    Note that a configuration set should only be constructed by loading from an
    existing database (in order to aggregate the info)

    Attributes:

        configuration_ids (list):
            A list of all attached configuration IDs

        description (str):
            A human-readable description of the configuration set

        aggregated_info (dict):
            A dictionary of information that was aggregated from all of the
            attached configurations. Contains the following information:

                * nconfigurations: the total number of configurations
                * nsites: the total number of sites
                * nelements: the total number of unique element types
                * elements: the element types
                * individual_elements_ratios: a set of elements ratios generated by
                  looping over each configuration, extracting its concentration of each
                  element, and adding the tuple of concentrations to the set
                * total_elements_ratios: the ratio of the total count of atoms of each
                  element type over nsites
                * chemical_formula_reduced: the set of all reduced chemical formulae
                * chemical_formula_anonymous: the set of all anonymous chemical formulae
                * chemical_formula_hill: the set of all hill chemical formulae
                * nperiodic_dimensions: the set of all numbers of periodic dimensions
                * dimension_types: the set of all periodic boundary choices

    """

    def __init__(self, config_df, name, description, dataset_id, ordered=False):
        self.name = name
        self.description = description
        self.dataset_id = dataset_id
        self.row_dict = self.to_row_dict(config_df)
        self.id = f"CS_{self.name}_{self.dataset_id}"
        cs_hash = sha512()
        cs_hash.update(self.id.encode("utf-8"))
        self._hash = cs_hash.hexdigest()
        self.row_dict["id"] = self.id
        self.row_dict["extended_id"] = f"{self.name}__{self.id}"
        self.row_dict["hash"] = self._hash

    def to_row_dict(self, config_df: list) -> dict:
        """Build configuration set row dict from a list of configuration row dicts.

        Args:
            config_df: List of row dicts as returned by dataset_query('configurations').
        """
        row_dict = _empty_dict_from_schema(configuration_set_schema)
        row_dict["name"] = self.name
        row_dict["description"] = self.description
        row_dict["last_modified"] = get_last_modified()
        row_dict["nconfigurations"] = len({c["id"] for c in config_df})
        row_dict["nsites"] = sum(c["nsites"] for c in config_df)

        elements_set = set()
        for c in config_df:
            elements_set.update(c["elements"] or [])
        row_dict["elements"] = sorted(elements_set)
        row_dict["nelements"] = len(row_dict["elements"])

        periodic_dims = set(
            c["nperiodic_dimensions"]
            for c in config_df
            if c["nperiodic_dimensions"] is not None
        )
        dim_types = set(
            tuple(c["dimension_types"])
            for c in config_df
            if c["dimension_types"]
        )
        row_dict["nperiodic_dimensions"] = sorted(periodic_dims)
        row_dict["dimension_types"] = [list(d) for d in sorted(dim_types)]

        total_atoms = row_dict["nsites"]
        element_counts: dict = {}
        for c in config_df:
            for atomic_num in (c["atomic_numbers"] or []):
                sym = ELEMENT_MAP[atomic_num]
                element_counts[sym] = element_counts.get(sym, 0) + 1
        row_dict["total_elements_ratios"] = (
            [
                element_counts.get(e, 0) / total_atoms
                for e in row_dict["elements"]
            ]
            if total_atoms > 0
            else []
        )

        row_dict["dataset_id"] = self.dataset_id
        return row_dict

    def __hash__(self):
        cs_hash = sha512()
        cs_hash.update(self.id.encode("utf-8"))
        return int(cs_hash.hexdigest(), 16)

    def __str__(self):
        return "ConfigurationSet(description='{}', nconfigurations={})".format(
            self.description,
            self.row_dict["nconfigurations"],
        )

    def __repr__(self):
        return str(self)
