import logging
from collections import Counter, namedtuple


from colabfit.tools.vast.schema import configuration_set_schema
from colabfit.tools.vast.data_object import DataObject
from colabfit.tools.vast.utils import (
    ELEMENT_MAP,
    _empty_dict_from_schema,
    get_last_modified,
)

logger = logging.getLogger(__name__)


class ConfigurationSet(DataObject):
    """
    A configuration set defines a group of configurations and aggregates
    information about those configurations to improve queries.

    Note that a configuration set should only be constructed by loading from an
    existing database (in order to aggregate the info)

    Attributes:

        configuration_ids (list):
            A list of all attached configuration IDs

        description (str):
            A human-readable description of the configuration set

        aggregated_info (dict):
            A dictionary of information that was aggregated from all of the
            attached configurations. Contains the following information:

                * nconfigurations: the total number of configurations
                * nsites: the total number of sites
                * nelements: the total number of unique element types
                * elements: the element types
                * individual_elements_ratios: a set of elements ratios generated by
                  looping over each configuration, extracting its concentration of each
                  element, and adding the tuple of concentrations to the set
                * total_elements_ratios: the ratio of the total count of atoms of each
                  element type over nsites
                * chemical_formula_reduced: the set of all reduced chemical formulae
                * chemical_formula_anonymous: the set of all anonymous chemical formulae
                * chemical_formula_hill: the set of all hill chemical formulae
                * nperiodic_dimensions: the set of all numbers of periodic dimensions
                * dimension_types: the set of all periodic boundary choices

    """

    def __init__(self, config_batches, name, description, dataset_id, ordered=False):
        self.name = name
        self.description = description
        self.dataset_id = dataset_id
        self.ordered = ordered
        self.id = f"CS_{self.name}_{self.dataset_id}"
        self.configuration_ids = []
        self.row_dict = self.to_row_dict(config_batches)
        self._generate_hash_and_id()

    def to_row_dict(self, config_batches):
        row_dict = _empty_dict_from_schema(configuration_set_schema)
        row_dict["name"] = self.name
        row_dict["description"] = self.description
        row_dict["dataset_id"] = self.dataset_id

        seen_props = set()
        seen_config_ids = set()
        nsites = 0
        seen_nperiodic = set()
        seen_dim_type_keys = set()
        unique_dim_types = []
        all_elements = set()
        element_counts = Counter()

        for batch in config_batches:
            prop_ids = batch.column("property_id").to_pylist()
            config_ids = batch.column("configuration_id").to_pylist()
            nsites_col = batch.column("nsites").to_pylist()
            nperiodic_col = batch.column("nperiodic_dimensions").to_pylist()
            dim_types_col = batch.column("dimension_types").to_pylist()
            elements_col = batch.column("elements").to_pylist()
            atomic_nums_col = batch.column("atomic_numbers").to_pylist()

            for i, prop_id in enumerate(prop_ids):
                if prop_id in seen_props:
                    continue
                seen_props.add(prop_id)
                if config_ids[i] is not None:
                    seen_config_ids.add(config_ids[i])
                nsites += nsites_col[i] or 0
                npd = nperiodic_col[i]
                if npd is not None:
                    seen_nperiodic.add(npd)
                dt = dim_types_col[i]
                if dt is not None:
                    key = tuple(dt)
                    if key not in seen_dim_type_keys:
                        seen_dim_type_keys.add(key)
                        unique_dim_types.append(dt)
                elems = elements_col[i]
                if elems:
                    all_elements.update(elems)
                nums = atomic_nums_col[i]
                if nums:
                    element_counts.update(nums)

        self.configuration_ids = sorted(seen_config_ids)
        row_dict["nconfigurations"] = len(seen_props)
        row_dict["nsites"] = nsites
        row_dict["nperiodic_dimensions"] = sorted(seen_nperiodic)
        row_dict["dimension_types"] = unique_dim_types
        row_dict["elements"] = sorted(list(all_elements))
        row_dict["nelements"] = len(row_dict["elements"])
        row_dict["last_modified"] = get_last_modified()

        total_elements = sum(element_counts.values())
        logger.info(f"{total_elements} {row_dict['nsites']}")
        assert total_elements == row_dict["nsites"]

        element_symbol_counts = {
            ELEMENT_MAP[num]: count for num, count in element_counts.items()
        }
        sorted_symbols = sorted(element_symbol_counts.keys())
        row_dict["total_elements_ratios"] = [
            element_symbol_counts[sym] / total_elements for sym in sorted_symbols
        ]

        row_dict["ordered"] = self.ordered
        row_dict["id"] = self.id
        row_dict["extended_id"] = self.id
        return row_dict

    def get_identifier_keys(self) -> list[str]:
        """Return the keys used for Dataset identification."""
        return ["id"]

    def __str__(self):
        return "ConfigurationSet(description='{}', nconfigurations={})".format(
            self.description,
            self.row_dict["nconfigurations"],
        )

    def __repr__(self):
        return str(self)


class ConfigurationSetInfo:
    """
    Simple class for holding information to generate a configuration set
    Attributes:
        co_name_match (str):
            A string to match against configuration names. If None, all names match.
        co_label_match (str):
            A string to match against configuration labels. If None, all labels match.
        cs_name (str):
            The name of the configuration set to create.
        cs_description (str):
            A human-readable description of the configuration set.
        ordered (bool):
            Whether the configurations in the set have intentional order.
    """

    configuration_set_info = namedtuple(
        "configuration_set_info",
        [
            "co_name_match",
            "co_label_match",
            "cs_name",
            "cs_description",
            "ordered",
        ],
    )

    def __init__(
        self,
        co_name_match: str = None,
        co_label_match: str = None,
        cs_name: str = None,
        cs_description: str = None,
        ordered: bool = False,
    ):
        self.co_name_match = co_name_match
        self.co_label_match = co_label_match
        self.cs_name = cs_name
        self.cs_description = cs_description
        self.ordered = ordered
        if not (self.co_name_match or self.co_label_match):
            raise ValueError("Must provide at least one of name or label match")

    def get_info(self):
        return self.configuration_set_info(
            co_name_match=self.co_name_match,
            co_label_match=self.co_label_match,
            cs_name=self.cs_name,
            cs_description=self.cs_description,
            ordered=self.ordered,
        )
